name: "Ar-Architecture"
description: "Website for testing AR"

url: 'https://ar-arq.github.io/' 
baseurl: ''

# Build settings
gems: [jekyll-paginate]
markdown: kramdown
highlighter: rouge
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


theme: jekyll-theme-slate